#' Merge probability matrix based on annotations
#'
#' @param pm A numeric matrix. Probability matrix generated by the soft_max function.
#' @param group_df A matrix. If `continuousAnnotation = FALSE`, it should be a 
#' character (or factor) matrix of discrete labels matching `pm`.  
#' If `continuousAnnotation = TRUE`, it should be a numeric fuzzy-annotation matrix
#'  (cells × types), where rows sum to 1.
#' @param continuousAnnotation Logical. If `TRUE`, interprets `group_df` as fuzzy 
#' probabilities instead of discrete labels.
#'
#' @return A probability matrix, describing the probability of each cell being
#' in each cellular neighborhood.
#' @export
#'
#' @examples
#'
#' data("spe_test")
#'
#' spe <- readHoodData(spe, anno_col = "celltypes")
#'
#' fnc <- findNearCells(spe, k = 100)
#'
#' pm <- scanHoods(fnc$distance)
#'
#' pm2 <- mergeByGroup(pm, fnc$cells)
#' 
#' # Fuzzy annotation example:
#' # Create a 10×3 fuzzy annotation, rows sum to 1
#' fuzzy_df <- matrix(runif(ncol(pm) * 3), ncol = 3)
#' fuzzy_df <- sweep(fuzzy_df, 1, rowSums(fuzzy_df), "/")
#' colnames(fuzzy_df) <- paste0("celltype_", seq(3))
#' pm_cont <- mergeByGroup(pm, fuzzy_df, continuousAnnotation = TRUE)
#'
mergeByGroup <- function(pm, group_df, continuousAnnotation = FALSE) {
  if (!is(pm, "matrix")){
    stop("The input pm must be a numeric matrix.")
  }
  df <- as.matrix(pm)
  group_df <- as.matrix(group_df)

  if (!continuousAnnotation){
      if (!all(dim(df) == dim(group_df))) {
          stop("df and group_df should have the same dimensions.")
      }
      colnames(df) <- colnames(group_df)
      rownames(df) <- rownames(group_df)
      uniquegroups <- sort(unique(as.vector((group_df))))
      out_df <- matrix(nrow = nrow(pm), ncol = length(uniquegroups))
      out_df <- vapply(uniquegroups, \(g) {
          mask <- 1 * (group_df == g)
          rowSums(mask * pm)[rownames(df)]
          }, numeric(nrow(df)))
      colnames(out_df) <- uniquegroups
      
  } else {
      if (!is.numeric(group_df)) {
          stop("When `continuousAnnotation = TRUE`, `group_df` must be numeric.")
      }
      if (nrow(group_df) != ncol(pm)) {
          stop("For continuous annotations, rows of `group_df` must match columns of `pm`.")
      }
      out_df <- pm %*% group_df               
      row_sums <- rowSums(out_df)
      out_df <- sweep(out_df, 1, row_sums, "/")
      colnames(out_df) <- colnames(group_df)
  }
  
  rownames(out_df) <- rownames(df)

  out_df[is.na(out_df)] <- 0

  return(out_df)
}
